### ISSUE TITLE
Unable to load the .m3u8 file

### ISSUE THREAD

**Issue by vivian4658** [samleong123/tonton_dailymotion_php#1]
Hi! Thanks for providing such an easy way to view local channels via m3u8! I've been using your links for quite sometime but I realized that the URLs stop working today, could it be due to the new token which you just loaded hours ago?

**Comment by samleong123** [comment]
Issue resolved , the server encountered some problem which affect the playlist update. Refer to here 
https://status.samsam123.name.my/incident/68803
