### ISSUE TITLE
TV3.m3u8 cannot stream.

### ISSUE THREAD

**Issue by zeehanz88** [samleong123/tonton_dailymotion_php#5]
Hi Sir, I'm not sure if you realised your TV3.m3u8 source cannot stream for weeks already. Could you please check the source? Thank you.

**Comment by samleong123** [comment]
![image](https://user-images.githubusercontent.com/58818070/165512228-3f03644c-ec0b-4ad7-b2d0-e2f5b064c321.png)
It seems like no problem on my side

**Comment by zeehanz88** [comment]
I tried stream this: https://raw.githubusercontent.com/samleong123/tonton_dailymotion_php/main/m3u8/TV3.m3u8
But cannot stream.

**Comment by samleong123** [comment]
> I tried stream this: https://raw.githubusercontent.com/samleong123/tonton_dailymotion_php/main/m3u8/TV3.m3u8 But cannot stream.

![image](https://user-images.githubusercontent.com/58818070/165516054-856a898a-0dd2-47c7-a3d1-e0086e15fc3d.png)
no problem on my side 
try check ur network and confirm its under Malaysia IP?

**Comment by zeehanz88** [comment]
Yes. It is under Malaysia IP. I tried stream other channels such as TV9.m3u8 from your source no problem.

**Comment by samleong123** [comment]
It seems like now Dailymotion started to implement verification of client's IP Address
If the IP Address doesn't matched with the one that request the metadata , it will return 403 
Not all videos affected , but can confirm TV3 is the one of the list
The only way is generate on your own using the PHP script in my repo and make sure watch it under the same network environment

**Comment by samleong123** [comment]
> Yes. It is under Malaysia IP. I tried stream other channels such as TV9.m3u8 from your source no problem.

Issue should be resolved , please try update your playlists with the latest one 
You can find it here : 
@weareblahs myfreeview : 
https://cdn.jsdelivr.net/gh/weareblahs/freeview@main/mytv_broadcasting.m3u8 (JSdelivr) 
https://github.com/weareblahs/freeview/raw/main/mytv_broadcasting.m3u8

Please let me know if your issue is resolved or just close it if its resolved
